name: CI/CD Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs: 
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14'

    - name: Install Dependencies
      run: npm install

    - name: Setup MySQL
      uses: mirromutth/mysql-action@v1.1
      with:
        mysql database: 'carwarshingday_test' 
        mysql user: 'test'
        mysql password: ${{ secrets.MYSQL_PASSWORD }}

    - name: Run Tests
      run: npm test
    - name: if fail
      uses: actions/github-script@v6
      env:
        SHOW_WORKSPACE_OUTPUT: ${{ steps.show-workspace.outputs.stdout }}
        SHOW_VAR_FILE_OUTPUT: ${{ steps.show-var-file.outputs.stdout }}
        SHOW_PLAN_OUTPUT: ${{ steps.show-plan.outputs.stdout }}
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        result-encoding: string
        script: |
          const output = `
          <details><summary>Show Plan</summary>
          \`\`\`\n
          ${process.env.SHOW_WORKSPACE_OUTPUT}
          ${process.env.SHOW_VAR_FILE_OUTPUT}
          ${process.env.SHOW_PLAN_OUTPUT}
          \`\`\`
          </details>
          `;
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: output
          })