name: CI/CD Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs: 
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14'
    - name: Install Dependencies
      run: npm install
    - name: Run Tests
      run: npm test
    - name: if fail
      uses: actions/github-script@0.9.0 # Use the latest version
      if: failure() # Correctly aligned with 'uses' and 'with'
      with:
          github-token: ${{ github.token }} # Use the correct token syntax
          script: |
            const ref = "${{ github.ref }}"
            const pull_number = Number(ref.split("/")[2])
            await github.pulls.createReview({
              ...context.repo,
              pull_number, # Correct syntax
              body: "Please check the test code again.",
              event: "REQUEST_CHANGES"
            })
            await github.pulls.update({
              ...context.repo,
              pull_number, # Correct syntax
              state: "closed"
            })